### ISSUE TITLE
Config travis ci

### ISSUE THREAD

**Issue by thminhVN** [dwarvesf/liulo-backend#6]
### Status

TASK

### Checklist

- [ ] Config travis to run CI/CD

### Description
- We want to config Travis run `test` and `credo` on Elixir 1.7.* when we push to branch name like `feature/*`, create pull request and develop
- Auto deploy with https://github.com/bitwalker/distillery to AWS on `develop` and `master` when it pass test

**Comment by MattMattV** [comment]
Hello ! :wave: 

I would like to know if this task is open to grab (:

**Comment by thminhVN** [comment]
Hi @MattMattV, Do you want to take this issue?

**Comment by MattMattV** [comment]
Absolutely !

Could you describe me which task you want to be ran on Travis ? (:

**Comment by thminhVN** [comment]
I just update issue description. Please ask me if you need more detail

**Comment by thminhVN** [comment]
You can create and work on branch `feature/travis-ci`

**Comment by MattMattV** [comment]
For the deployment part, is your AWS service is listed [here](https://docs.travis-ci.com/user/deployment/) ? Otherwise, which service do you use ?

**Comment by MattMattV** [comment]
You can see [here](https://travis-ci.org/dwarvesf/liulo-backend/builds/435549922) that Credo and your tests are run Travis _via_ the existing tasks you already defined in the Makefile :tada:
